// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnWD_KQIbpjog7flVjQ_30KKPQqMfpW9o',
    appId: '1:73423606526:web:6491688360b1549b88cbaf',
    messagingSenderId: '73423606526',
    projectId: 'event-e5a49',
    authDomain: 'event-e5a49.firebaseapp.com',
    storageBucket: 'event-e5a49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8HtGkkZddscL-nXI_fVV3RUCrr8CxV5M',
    appId: '1:73423606526:android:e581281511832daa88cbaf',
    messagingSenderId: '73423606526',
    projectId: 'event-e5a49',
    storageBucket: 'event-e5a49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd72x-gTjW5qmhw6A_63goyceU5mHhKn0',
    appId: '1:73423606526:ios:f9bfe4584560144588cbaf',
    messagingSenderId: '73423606526',
    projectId: 'event-e5a49',
    storageBucket: 'event-e5a49.appspot.com',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd72x-gTjW5qmhw6A_63goyceU5mHhKn0',
    appId: '1:73423606526:ios:f9bfe4584560144588cbaf',
    messagingSenderId: '73423606526',
    projectId: 'event-e5a49',
    storageBucket: 'event-e5a49.appspot.com',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnWD_KQIbpjog7flVjQ_30KKPQqMfpW9o',
    appId: '1:73423606526:web:0aa7ae72545c1ca288cbaf',
    messagingSenderId: '73423606526',
    projectId: 'event-e5a49',
    authDomain: 'event-e5a49.firebaseapp.com',
    storageBucket: 'event-e5a49.appspot.com',
  );
}
